# Generated by Django 2.2 on 2021-09-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0009_auto_20210915_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
